### ISSUE TITLE
Project Point Tracking

### ISSUE THREAD

**Issue by CaretCake** [CaretCake/FiestaMarket#7]
**Search - 16**
- [x] 4 - Searching is done through database queries on item database
- [x] 1 - Results can be sorted and filtered (by class, level, type, price, tag, etc)
- [x] 2 - Typing into search bar gives suggestions based on known items
- [x] 2 - Viewing search results does not require login, but further features do
- [ ] 7 - Set a "watch" on a specified item to receive notification when item fitting requirements is posted

**Account Management & Creation - 6**
- [x] 3 - Create account through form
- [x] 1 - Set status (online, online in-game, offline)
- [x] 1 - Set contact information
- [x] 1 - Set contact preference (in-game, discord, website)

**Messaging - 6**
- [ ] 6 - Message buyer/seller user via website

**Orders - 36**
- [x] 2 - Keep history of sales of items 
- [x] 2 - Provide average price based on historical sales/purchases recorded on the site for same item
- [x] 2 - Automatically adjust timeframe of historical price data provided based on data available for item
- [x] 3 - Suggest a price for buy/sell orders of an item using information from historical data, considering only that it’s the same type of item
- [ ] 6 - Suggest a price for buy/sell orders of an item using information from historical data, considering same type of item as well as weighting price according to stats and desired stats of historical items and posted item
- [ ] 2 - Posted orders automatically expire after x amount of time and notify poster upon expiration
*Sell Orders*
- [x] 5 - Post an item for sale
- [x] 1 - Set specific item stats
- [x] 1 - Set a “Buy It Now” price
- [x] 1 - Set preference of open or not open to offers
- [x] 2 - Buyers can place bids on items open to offers
- [ ] 1 - Buyers can “buy” an item, marking it as “pending sale” while still visible to other users (prevents people from fake “buying” items to remove it from listings)
- [x] 1 - Mark item as sold
*Buy Orders*
- [x] 5 - Post a buy order for an item
- [x] 1 - Set desired stat ranges
- [x] 1 - Set price/price range
- [x] 1 - Mark item as bought

**General - 19**
- [ ] 2 - Give positive/negative feedback on user which affects user's reputation
- [ ] 2 - System to report users
- [x] 2 - Form to provide feedback on the site/report bugs
- [x] 6 - Some form of admin account
- [ ] 7 - Notifications (message received, bid on posted item, outbid, etc.)

**Languages and Libraries - 35 **
- [x] 6 - Front-end library (React or Mithril)
- [x] 1 - Node.js
- [x] 1 - Express.js
- [x] 1 - SASS
- [x] 5 - Set-up server for hosting through AWS
- [x] 1- HTTPS
- [x] 1 - SQL
- [x] 6 - GraphQL
- [x] 6 - Database set-up
- [x] 2 - Aesthetically pleasing, reactive design
- [x] 2 - Tested code
- [x] 1 - Github version control used
- [x] 1 - Beta/User testing
- [x] 1 - Kanban or similar issue tracking method
